/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TodayRouteImport } from './routes/today'
import { Route as WidgetPreviewRouteImport } from './routes/widget-preview'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsStoryIdRouteImport } from './routes/news.$storyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetPreviewRoute = WidgetPreviewRouteImport.update({
  id: '/widget-preview',
  path: '/widget-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsStoryIdRoute = NewsStoryIdRouteImport.update({
  id: '/news/$storyId',
  path: '/news/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/widget-preview': typeof WidgetPreviewRoute
  '/news/$storyId': typeof NewsStoryIdRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/widget-preview': typeof WidgetPreviewRoute
  '/news/$storyId': typeof NewsStoryIdRoute
  '/news': typeof NewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/widget-preview': typeof WidgetPreviewRoute
  '/news/$storyId': typeof NewsStoryIdRoute
  '/news/': typeof NewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/settings'
    | '/today'
    | '/widget-preview'
    | '/news/$storyId'
    | '/news/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/settings'
    | '/today'
    | '/widget-preview'
    | '/news/$storyId'
    | '/news'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/settings'
    | '/today'
    | '/widget-preview'
    | '/news/$storyId'
    | '/news/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  SettingsRoute: typeof SettingsRoute
  TodayRoute: typeof TodayRoute
  WidgetPreviewRoute: typeof WidgetPreviewRoute
  NewsStoryIdRoute: typeof NewsStoryIdRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget-preview': {
      id: '/widget-preview'
      path: '/widget-preview'
      fullPath: '/widget-preview'
      preLoaderRoute: typeof WidgetPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$storyId': {
      id: '/news/$storyId'
      path: '/news/$storyId'
      fullPath: '/news/$storyId'
      preLoaderRoute: typeof NewsStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  SettingsRoute: SettingsRoute,
  TodayRoute: TodayRoute,
  WidgetPreviewRoute: WidgetPreviewRoute,
  NewsStoryIdRoute: NewsStoryIdRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
